apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestration-platform
  template:
    metadata:
      labels:
        app: orchestration-platform
    spec:
      containers:
      - name: orchestration-platform
        image: myrepo/orchestration-platform:latest
        ports:
        - containerPort: 8080
