apiVersion: v1
kind: Service
metadata:
  name: orchestration-platform
spec:
  selector:
    app: orchestration-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
