name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test
    - name: Deploy to EKS
      if: github.ref == 'refs/heads/main'
      run: |
        aws eks update-kubeconfig --name orchestration-platform
        kubectl apply -f k8s/
